# -*- coding: utf-8 -*-
"""
Automatically generated by Colaboratory.

# Homework Week 6

## Imam Syahrizal
## 18/424967/TK/46662
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy.random import randn

# Define V
# time sampling
t = np.linspace(0,1,100)

# v
v = np.sin(10*t) + randn(1)

"""## HOMEWORK 1 : Auto Reggresive

"""

# weight
a = np.array([4,6,6,6,2])*0.1

u = [] # agar aman jika di run ulang karena pakai append di bagian bawah
u = [v[0]]
print(u)

for n in range(1,len(v)):
  un_temp = v[n]
  for i in range(len(a)):
    if(n-i>0):
      un_temp = un_temp - a[i]*u[n-i-1]
  u = np.append(u,un_temp)

print(v)

print(u)

plt.plot(t,v,'r',t,u,'b')
plt.legend(('v','u'), loc = 'upper right')
plt.title('Auto Reggressive')

"""## Homework 2 : Moving Average
"""
# weight
b = np.array([4, 6, 6, 6, 2])*0.1

u2 = []
u2 = [v[0]]
print(u2)

for k in range(1, len(v)):
  u_temp = v[k]
  for m in range(len(b)):
    if(k-m>0):
      u_temp = u_temp + b[m]*v[k-m-1]
  u2 = np.append(u2, u_temp)

print(u2)

plt.plot(t,v,'r',t,u2,'b')
plt.legend(('v','u'), loc = 'upper right')
plt.title('Moving Average')

"""## Homework 3 : ARMA Generator
"""

a = np.array([4, 2, 4, 9, 6, 7])*0.1
b = np.array([4, 6, 6, 6, 2])*0.1

u3 = []
u3= [v[0]]

for n in range(1, len(v)):
  temp = v[n]
  for m in range(len(a)):
    if(n-m>0):
      temp = temp - a[m]*u[n-m-1]
  for k in range(len(b)):
    if(n-k>0):
      temp = temp + b[k]*v[n-k-1]
  u3 = np.append(u3, temp)

v[3] + b[0]*v[2] + b[1]*v[1] + b[2]*v[0] - a[0]*u[2] - a[1]*u[1] - a[2]*u[0] # test untuk u[3] >> u(4)

u3

plt.plot(t,v,'r',t,u3,'b')
plt.legend(('v','u'), loc = 'upper right')
plt.title('ARMA')